apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilienceops
  labels:
    app: resilienceops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resilienceops
  template:
    metadata:
      labels:
        app: resilienceops
    spec:
      containers:
        - name: resilienceops
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
